name: Eslint

on:
  pull_request:
    branches: ['dev']

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: setupNodeVersion
        uses: actions/setup-node@v4
        with:
          node-version: 20.4.0
      - name: Install dependencies
        run: yarn install

      - name: Run eslint
        run: yarn run lint
